"""
This type stub file was generated by pyright.
"""

from .widget import Widget
from .widget_layout import Layout
from .trait_types import InstanceDict

"""Contains the DOMWidget class"""
class DOMWidget(Widget):
    """Widget that can be inserted into the DOM

    Parameters
    ----------
    tooltip: str
       tooltip caption
    layout: InstanceDict(Layout)
       widget layout
    """
    _model_name = ...
    _dom_classes = ...
    tabbable = ...
    tooltip = ...
    layout: Layout
    def add_class(self, className): # -> Self@DOMWidget:
        """
        Adds a class to the top level element of the widget.

        Doesn't add the class if it already exists.
        """
        ...
    
    def remove_class(self, className): # -> Self@DOMWidget:
        """
        Removes a class from the top level element of the widget.

        Doesn't remove the class if it doesn't exist.
        """
        ...
    
    def focus(self): # -> None:
        """
        Focus on the widget.
        """
        ...
    
    def blur(self): # -> None:
        """
        Blur the widget.
        """
        ...
    


