"""
This type stub file was generated by pyright.
"""

from .widget import Widget

"""Contains the ValueWidget class"""
class ValueWidget(Widget):
    """Widget that can be used for the input of an interactive function"""
    value = ...
    def get_interact_value(self): # -> Any:
        """Return the value for this widget which should be passed to
        interactive functions. Custom widgets can change this method
        to process the raw value ``self.value``.
        """
        ...
    


