"""
This type stub file was generated by pyright.
"""

from .widget_description import DescriptionWidget
from .valuewidget import ValueWidget
from .widget import register
from .widget_core import CoreWidget

"""Color class.

Represents an HTML Color .
"""
@register
class ColorPicker(DescriptionWidget, ValueWidget, CoreWidget):
    value = ...
    concise = ...
    disabled = ...
    _view_name = ...
    _model_name = ...


