"""
This type stub file was generated by pyright.
"""

from .widget import Widget

"""Base widget class for widgets provided in Core"""
class CoreWidget(Widget):
    _model_module = ...
    _model_module_version = ...
    _view_module = ...
    _view_module_version = ...


