"""
This type stub file was generated by pyright.
"""

from .widget import Widget, register
from .widget_style import Style
from .widget_core import CoreWidget
from .domwidget import DOMWidget

"""Contains the DOMWidget class"""
@register
class DescriptionStyle(Style, CoreWidget, Widget):
    """Description style widget."""
    _model_name = ...
    description_width = ...


class DescriptionWidget(DOMWidget, CoreWidget):
    """Widget that has a description label to the side."""
    _model_name = ...
    description = ...
    description_allow_html = ...
    style = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    @property
    def description_tooltip(self):
        """The tooltip information.
        .. deprecated :: 8.0.0
           Use tooltip attribute instead.
        """
        ...
    
    @description_tooltip.setter
    def description_tooltip(self, tooltip): # -> None:
        ...
    


