"""
This type stub file was generated by pyright.
"""

from .widget import Widget

"""Contains the Style class"""
class Style(Widget):
    """Style specification"""
    _model_name = ...
    _view_name = ...
    _view_module = ...
    _view_module_version = ...


