"""
This type stub file was generated by pyright.
"""

from .valuewidget import ValueWidget
from .widget import register
from .widget_core import CoreWidget
from .widget_description import DescriptionWidget

"""
Time picker widget
"""
@register
class TimePicker(DescriptionWidget, ValueWidget, CoreWidget):
    """
    Display a widget for picking times.

    Parameters
    ----------

    value: datetime.time
        The current value of the widget.

    disabled: bool
        Whether to disable user changes.

    min: datetime.time
        The lower allowed time bound

    max: datetime.time
        The upper allowed time bound

    step: float | 'any'
        The time step to use for the picker, in seconds, or "any"

    Examples
    --------

    >>> import datetime
    >>> import ipydatetime
    >>> time_pick = ipydatetime.TimePicker()
    >>> time_pick.value = datetime.time(12, 34, 3)
    """
    _view_name = ...
    _model_name = ...
    value = ...
    disabled = ...
    min = ...
    max = ...
    step = ...


