"""
This type stub file was generated by pyright.
"""

"""Module that implements mocking Vega date and time functions."""
date_time_functions = ...
error_message = ...
def now():
    """Return the timestamp for the current time."""
    ...

def datetime(year, month, day, hour, min, sec, millisec):
    """Return a new Date instance. The month is 0-based, such that 1 represents February."""
    ...

def date(datetime):
    """Return the day of the month for the given datetime value, in local time."""
    ...

def day(datetime):
    """Return the day of the week for the given datetime value, in local time."""
    ...

def year(datetime):
    """Return the year for the given datetime value, in local time."""
    ...

def quarter(datetime):
    """Return the quarter of the year (0-3): for the given datetime value, in local time."""
    ...

def month(datetime):
    """Return the (zero-based): month for the given datetime value, in local time."""
    ...

def hours(datetime):
    """Return the hours component for the given datetime value, in local time."""
    ...

def minutes(datetime):
    """Return the minutes component for the given datetime value, in local time."""
    ...

def seconds(datetime):
    """Return the seconds component for the given datetime value, in local time."""
    ...

def milliseconds(datetime):
    """Return the milliseconds component for the given datetime value, in local time."""
    ...

def time(datetime):
    """Return the epoch-based timestamp for the given datetime value."""
    ...

def timezoneoffset(datetime):
    """Return the timezone offset from the local timezone to UTC for the given datetime value."""
    ...

def utc(year, month, day, hour, min, sec, millisec):
    """Return a timestamp for the given UTC date. The month is 0-based, such that 1 represents February."""
    ...

def utcdate(datetime):
    """Return the day of the month for the given datetime value, in UTC time."""
    ...

def utcday(datetime):
    """Return the day of the week for the given datetime value, in UTC time."""
    ...

def utcyear(datetime):
    """Return the year for the given datetime value, in UTC time."""
    ...

def utcquarter(datetime):
    """Return the quarter of the year (0-3): for the given datetime value, in UTC time."""
    ...

def utcmonth(datetime):
    """Return the (zero-based): month for the given datetime value, in UTC time."""
    ...

def utchours(datetime):
    """Return the hours component for the given datetime value, in UTC time."""
    ...

def utcminutes(datetime):
    """Return the minutes component for the given datetime value, in UTC time."""
    ...

def utcseconds(datetime):
    """Return the seconds component for the given datetime value, in UTC time."""
    ...

def utcmilliseconds(datetime):
    """Return the milliseconds component for the given datetime value, in UTC time."""
    ...

