"""
This type stub file was generated by pyright.
"""

"""Formatting module that implements mocking Vega formatting functions."""
formatting_functions = ...
error_message = ...
def dayFormat(day):
    """Format a (0-6) weekday number as a full week day name, according to the current locale.

    For example: dayFormat(0) -> "Sunday".
    """
    ...

def dayAbbrevFormat(day):
    """Format a (0-6) weekday number as an abbreviated week day name, according to the current locale.

    For example: dayAbbrevFormat(0) -> "Sun".
    """
    ...

def format(value, specifier):
    """Format a numeric value as a string.

    The specifier must be a valid d3-format specifier (e.g., format(value, ',.2f').
    """
    ...

def monthFormat(month):
    """Format a (zero-based) month number as a full month name, according to the current locale.

    For example: monthFormat(0) -> "January".
    """
    ...

def monthAbbrevFormat(month):
    """Format a (zero-based) month number as an abbreviated month name, according to the current locale.

    For example: monthAbbrevFormat(0) -> "Jan".
    """
    ...

def timeFormat(value, specifier):
    """Format a datetime value (either a Date object or timestamp) as a string, according to the local time.

    The specifier must be a valid d3-time-format specifier. For example: timeFormat(timestamp, '%A').
    """
    ...

def timeParse(string, specifier):
    """Parse a string value to a Date object, according to the local time.

    The specifier must be a valid d3-time-format specifier. For example: timeParse('June 30, 2015', '%B %d, %Y').
    """
    ...

def utcFormat(value, specifier):
    """Format a datetime value (either a Date object or timestamp) as a string, according to UTC time.

    The specifier must be a valid d3-time-format specifier. For example: utcFormat(timestamp, '%A').
    """
    ...

def utcParse(value, specifier):
    """Parse a string value to a Date object, according to UTC time.

    The specifier must be a valid d3-time-format specifier. For example: utcParse('June 30, 2015', '%B %d, %Y').
    """
    ...

