"""
This type stub file was generated by pyright.
"""

"""Math module that implements mocking Vega mathematical functions."""
math_functions = ...
error_message = ...
def isNaN(value):
    """Return true if value is not a number. Same as JavaScript’s isNaN."""
    ...

def isFinite(value):
    """Return true if value is a finite number. Same as JavaScript’s isFinite."""
    ...

def abs(value):
    """Returns the absolute value of value. Same as JavaScript’s Math.abs."""
    ...

def acos(value):
    """Trigonometric arccosine. Same as JavaScript’s Math.acos."""
    ...

def asin(value):
    """Trigonometric arcsine. Same as JavaScript’s Math.asin."""
    ...

def atan(value):
    """Trigonometric arctangent. Same as JavaScript’s Math.atan."""
    ...

def atan2(dy, dx):
    """Returns the arctangent of dy / dx. Same as JavaScript’s Math.atan2."""
    ...

def ceil(value):
    """Rounds value to the nearest integer of equal or greater value. Same as JavaScript’s Math.ceil."""
    ...

def clamp(value, min, max):
    """Restricts value to be between the specified min and max."""
    ...

def cos(value):
    """Trigonometric cosine. Same as JavaScript’s Math.cos."""
    ...

def exp(exponent):
    """Returns the value of e raised to the provided exponent. Same as JavaScript’s Math.exp."""
    ...

def floor(value):
    """Rounds value to the nearest integer of equal or lower value. Same as JavaScript’s Math.floor."""
    ...

def log(value):
    """Returns the natural logarithm of value. Same as JavaScript’s Math.log."""
    ...

def max(*values):
    """Returns the maximum argument value. Same as JavaScript’s Math.max."""
    ...

def min(*values):
    """Returns the minimum argument value. Same as JavaScript’s Math.min."""
    ...

def pow(value, exponent):
    """Returns value raised to the given exponent. Same as JavaScript’s Math.pow."""
    ...

def random():
    """Returns a pseudo-random number in the range [0,1). Same as JavaScript’s Math.random."""
    ...

def round(value):
    """Rounds value to the nearest integer. Same as JavaScript’s Math.round."""
    ...

def sin(value):
    """Trigonometric sine. Same as JavaScript’s Math.sin."""
    ...

def sqrt(value):
    """Square root function. Same as JavaScript’s Math.sqrt."""
    ...

def tan(value):
    """Trigonometric tangent. Same as JavaScript’s Math.tan."""
    ...

