"""
This type stub file was generated by pyright.
"""

"""Module that implements mocking Vega type checking functions."""
type_checking_functions = ...
error_message = ...
def isArray(value):
    """Return true if value is an array, false otherwise."""
    ...

def isBoolean(value):
    """Return true if value is a boolean (true or false), false otherwise."""
    ...

def isDate(value):
    """
    Return true if value is a Date object, false otherwise.

    This method will return false for timestamp numbers or date-formatted strings; it recognizes Date objects only.
    """
    ...

def isDefined(value):
    """
    Return true if value is a defined value, false if value equals undefined.

    This method will return true for null and NaN values.
    """
    ...

def isNumber(value):
    """Return true if value is a number, false otherwise. NaN and Infinity are considered numbers."""
    ...

def isObject(value):
    """Return true if value is an object (including arrays and Dates), false otherwise."""
    ...

def isRegExp(value):
    """Return true if value is a RegExp (regular expression) object, false otherwise."""
    ...

def isString(value):
    """Return true if value is a string, false otherwise."""
    ...

def isValid(value):
    """Return true if value is not null, undefined, or NaN, false otherwise."""
    ...

