"""
This type stub file was generated by pyright.
"""

"""Module that implements mocking Vega type coercing functions."""
type_coercing_functions = ...
error_message = ...
def toBoolean(value):
    """Coerce the input value to a string. None values and empty strings are mapped to None."""
    ...

def toDate(value):
    """Coerce the input value to a Date instance. None values and empty strings are mapped to None.

    If an optional parser function is provided, it is used to perform date parsing, otherwise Date.parse is used.
    Be aware that Date.parse has different implementations across browsers!
    """
    ...

def toNumber(value):
    """Coerce the input value to a number. None values and empty strings are mapped to None."""
    ...

def toString(value):
    """Coerce the input value to a string. None values and empty strings are mapped to None."""
    ...

